# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AnimesDiscovery' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AnimesDiscovery
  pod 'SnapKit', '~> 5.6.0'
  pod 'Alamofire'
  pod 'AlamofireImage', '~> 4.1'
end
